- packages/clerk_auth/.pubignore
- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_api/token_cache.dart
- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/clerk_auth/http_client.dart
- packages/clerk_auth/lib/src/clerk_auth/persistor.dart
- packages/clerk_auth/lib/src/models/api_response.dart
- packages/clerk_auth/lib/src/models/environment/auth_config.dart
- packages/clerk_auth/lib/src/models/environment/display_config.dart
- packages/clerk_auth/lib/src/models/environment/user_settings.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_in_test.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_up_test.dart
- packages/clerk_auth/test/test_helpers.dart
- packages/clerk_flutter/example/.pubignore
- packages/clerk_flutter/example/lib/main.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth_provider.dart
* feat: add regular poll for session token [CLERK_SDK #42]
* feat: add poll mode configuration to clerk_flutter [CLERK_SDK #42]
* fix: pr changes
---------
Closes #42
> feat: add regular poll for session token [CLERK_SDK #42] (#43)

- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_api/token_cache.dart
- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/models/helpers.dart
- packages/clerk_auth/test/integration/clerk_api/sign_in_test.dart
- packages/clerk_auth/test/integration/clerk_api/sign_up_test.dart
- packages/clerk_auth/test/integration/clerk_api/user_details_test.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_in_test.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_up_test.dart
> fix: use utc for token expiry timestamps #47

- packages/clerk_auth/CHANGELOG.md
- packages/clerk_auth/README.md
- packages/clerk_auth/pubspec.yaml
- packages/clerk_flutter/CHANGELOG.md
- packages/clerk_flutter/README.md
- packages/clerk_flutter/lib/src/widgets/organization/clerk_create_organization_widget.dart
- packages/clerk_flutter/lib/src/widgets/organization/clerk_organization_profile_widget.dart
- packages/clerk_flutter/lib/src/widgets/organization/clerk_organization_switcher_widget.dart
- packages/clerk_flutter/pubspec.yaml
- packages/clerk_widgetbook/lib/widgets/organization/clerk_create_organization_widget.dart
- packages/clerk_widgetbook/lib/widgets/organization/clerk_organization_profile_widget.dart
- packages/clerk_widgetbook/lib/widgets/organization/clerk_organization_switcher_widget.dart
> chore: release v0.0.4-dev #51

- packages/clerk_flutter/lib/src/widgets/control/clerk_auth.dart
- packages/clerk_flutter/lib/src/widgets/user/clerk_user_button.dart
> fix: switch add account routing from overlays to routes #58

- packages/clerk_auth/README.md
- packages/clerk_auth/example/main.dart
- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_api/token_cache.dart
- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/models/helpers.dart
- packages/clerk_auth/lib/src/utils/extensions.dart
- packages/clerk_auth/pubspec.yaml
- packages/clerk_auth/test/integration/clerk_api/environment_test.dart
- packages/clerk_auth/test/integration/clerk_api/sign_in_test.dart
- packages/clerk_auth/test/integration/clerk_api/sign_up_test.dart
- packages/clerk_auth/test/integration/clerk_api/user_details_test.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_in_test.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_up_test.dart
- packages/clerk_auth/test/test_helpers.dart
- packages/clerk_auth/test/unit/clerk_api/clerk_api_test.dart
- packages/clerk_flutter/README.md
- packages/clerk_flutter/example/README.md
- packages/clerk_flutter/example/lib/main.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth_provider.dart
> fix: remove public_key #45

- packages/clerk_auth/lib/clerk_auth.dart
- packages/clerk_auth/lib/src/clerk_auth/persistor.dart
- packages/clerk_auth/lib/src/utils/extensions.dart
- packages/clerk_flutter/README.md
- packages/clerk_flutter/example/lib/main.dart
- packages/clerk_flutter/example/pubspec.yaml
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth_provider.dart
- packages/clerk_flutter/pubspec.yaml
> feat: add persistor #46

- packages/clerk_auth/analysis_options.yaml
- packages/clerk_flutter/analysis_options.yaml
- packages/clerk_flutter/example/pubspec.yaml
- packages/clerk_flutter/pubspec.yaml
- packages/clerk_widgetbook/analysis_options.yaml
- packages/clerk_widgetbook/pubspec.yaml
> fix: lower flutter version to 3.7.0

- packages/clerk_auth/lib/src/models/environment/environment.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_authentication_widget.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_in_panel.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_up_panel.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sso_panel.dart
- packages/clerk_flutter/lib/src/widgets/ui/clerk_code_input.dart
- packages/clerk_flutter/lib/src/widgets/ui/multi_digit_code_input.dart
> fix: fix UI when strategies are missing #65

- packages/clerk_auth/lib/clerk_auth.dart
- packages/clerk_auth/lib/clerk_constants.dart
- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_auth/http_client.dart
> feat: add additional http request headers #76

- packages/clerk_auth/lib/src/models/client.g.dart
- packages/clerk_auth/lib/src/models/email.g.dart
- packages/clerk_auth/lib/src/models/environment/display_config.dart
- packages/clerk_auth/lib/src/models/environment/display_config.g.dart
- packages/clerk_auth/lib/src/models/factor.g.dart
- packages/clerk_auth/lib/src/models/organization.g.dart
- packages/clerk_auth/lib/src/models/organization_membership.g.dart
- packages/clerk_auth/lib/src/models/passkey.g.dart
- packages/clerk_auth/lib/src/models/phone_number.g.dart
- packages/clerk_auth/lib/src/models/session.g.dart
- packages/clerk_auth/lib/src/models/sign_in.g.dart
- packages/clerk_auth/lib/src/models/sign_up.g.dart
- packages/clerk_auth/lib/src/models/user.g.dart
- packages/clerk_auth/lib/src/models/verification.g.dart
- packages/clerk_auth/lib/src/models/web3_wallet.g.dart
> fix: remove favicon_image from display_config [#88]

- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_auth/http_client.dart
- packages/clerk_auth/pubspec.yaml
- packages/clerk_auth/test/test_helpers.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_in_panel.dart
> fix: change sendfile to sendbytestream [#79]

- packages/clerk_flutter/lib/src/utils/clerk_telemetry.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth.dart
> fix: make clerkauthstate available in clerk_auth telemetry [#103]

- packages/clerk_auth/lib/src/models/client/organization_membership.dart
- packages/clerk_auth/lib/src/models/client/organization_membership.g.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_in_panel.dart
- packages/clerk_flutter/lib/src/widgets/ui/clerk_input_dialog.dart
- packages/clerk_flutter/lib/src/widgets/ui/clerk_material_button.dart
> fix: remove dependency on alertdialog [#80]

- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/models/client/external_account.dart
- packages/clerk_auth/lib/src/models/client/verification.dart
- packages/clerk_auth/lib/src/models/client/verification.g.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_error_listener.dart
- packages/clerk_flutter/lib/src/widgets/user/clerk_user_profile.dart
- packages/clerk_flutter/lib/src/widgets/user/connect_account_panel.dart
> fix: connecting a new account [#121]

- packages/clerk_auth/lib/clerk_auth.dart
- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_in_test.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_up_test.dart
- packages/clerk_flutter/example/lib/main.dart
- packages/clerk_flutter/lib/src/clerk_auth_state.dart
- packages/clerk_flutter/lib/src/widgets/organization/clerk_organization_list.dart
- packages/clerk_flutter/lib/src/widgets/user/clerk_user_button.dart
> fix: surface server errors in the ui [#122]

- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/clerk_auth/auth_error.dart
- packages/clerk_flutter/README.md
- packages/clerk_flutter/example/lib/main.dart
- packages/clerk_flutter/lib/src/clerk_auth_state.dart
- packages/clerk_flutter/lib/src/clerk_loading_overlay.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_in_panel.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_error_listener.dart
- packages/clerk_flutter/lib/src/widgets/organization/clerk_organization_list.dart
- packages/clerk_flutter/lib/src/widgets/ui/clerk_loading_overlay.dart
- packages/clerk_flutter/lib/src/widgets/ui/clerk_text_form_field.dart
- packages/clerk_flutter/lib/src/widgets/ui/closeable.dart
> fix: amalgamate closeable and animatedcloseable [#138]

- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/models/status.dart
- packages/clerk_flutter/l10n/en.arb
- packages/clerk_flutter/lib/src/generated/clerk_sdk_localizations.dart
- packages/clerk_flutter/lib/src/generated/clerk_sdk_localizations_en.dart
- packages/clerk_flutter/lib/src/utils/localization_extensions.dart
> fix: add translations for sign in error [#143]

- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_flutter/lib/src/utils/localization_extensions.dart
Resolves #147 
@slightfoot A slight refactor to the stuff we did on attemptsignin which is more in keeping with the way the rest of it works. Feel free to kill it if you don't like it.
> fix: refactor attemptSignIn [#147]

- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_api/token_cache.dart
- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/clerk_auth/http_service.dart
- packages/clerk_auth/test/test_helpers.dart
- packages/clerk_flutter/lib/src/clerk_auth_state.dart
> fix: refactor HttpService

- packages/clerk_auth/CHANGELOG.md
- packages/clerk_auth/lib/src/_version.dart
- packages/clerk_auth/pubspec.yaml
- packages/clerk_flutter/CHANGELOG.md
- packages/clerk_flutter/pubspec.yaml
> chore: release v0.0.7-dev

- packages/clerk_flutter/lib/src/clerk_auth_state.dart
- packages/clerk_flutter/lib/src/utils/clerk_auth_config.dart
- packages/clerk_flutter/pubspec.yaml
- packages/clerk_flutter/test/widgets/clerk_loading_overlay_test.dart
Adds support for `fallbackLocalization` to `ClerkAuthConfig`
> feat: support fall-back localization default English #163

- packages/clerk_auth/lib/src/clerk_constants.dart
- packages/clerk_flutter/lib/src/clerk_auth_state.dart
> fix: update user agent [#166]

- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/models/client/strategy.dart
- packages/clerk_flutter/example/android/app/build.gradle
- packages/clerk_flutter/example/android/app/src/main/AndroidManifest.xml
- packages/clerk_flutter/example/android/build.gradle
- packages/clerk_flutter/example/android/gradle/wrapper/gradle-wrapper.properties
- packages/clerk_flutter/example/ios/Podfile
- packages/clerk_flutter/example/ios/Podfile.lock
- packages/clerk_flutter/example/ios/Runner.xcodeproj/project.pbxproj
- packages/clerk_flutter/example/ios/Runner/Info.plist
- packages/clerk_flutter/example/lib/main.dart
- packages/clerk_flutter/example/linux/flutter/generated_plugin_registrant.cc
- packages/clerk_flutter/example/linux/flutter/generated_plugins.cmake
- packages/clerk_flutter/example/macos/Flutter/GeneratedPluginRegistrant.swift
- packages/clerk_flutter/example/pubspec.yaml
- packages/clerk_flutter/example/windows/flutter/generated_plugin_registrant.cc
- packages/clerk_flutter/example/windows/flutter/generated_plugins.cmake
- packages/clerk_flutter/l10n/en.arb
- packages/clerk_flutter/lib/src/clerk_auth_state.dart
- packages/clerk_flutter/lib/src/generated/clerk_sdk_localizations.dart
- packages/clerk_flutter/lib/src/generated/clerk_sdk_localizations_en.dart
- packages/clerk_flutter/lib/src/utils/clerk_auth_config.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_authentication.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth.dart
- packages/clerk_flutter/lib/src/widgets/organization/clerk_organization_profile.dart
- packages/clerk_flutter/lib/src/widgets/ui/platform_styled_dialog.dart
- packages/clerk_flutter/lib/src/widgets/user/clerk_user_button.dart
- packages/clerk_flutter/pubspec.yaml
Adds the capability to define custom schemes, and allow SSO through the device's browser to complete via a deep link into the host app
Resolves #170
> feat: allow app defined redirects [#170]

- packages/clerk_flutter/lib/src/clerk_auth_state.dart
- packages/clerk_flutter/lib/src/utils/clerk_auth_config.dart
> feat: clear cookies on sign out [#188]

- packages/clerk_auth/example/main.dart
- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_api/telemetry.dart
- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/clerk_auth/auth_config.dart
- packages/clerk_auth/lib/src/clerk_auth/http_service.dart
- packages/clerk_auth/lib/src/clerk_auth/persistor.dart
- packages/clerk_auth/test/integration/clerk_api/environment_test.dart
- packages/clerk_auth/test/integration/clerk_api/sign_in_test.dart
- packages/clerk_auth/test/integration/clerk_api/sign_up_test.dart
- packages/clerk_auth/test/integration/clerk_api/user_details_test.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_in_test.dart
- packages/clerk_auth/test/integration/clerk_auth/sign_up_test.dart
- packages/clerk_auth/test/test_helpers.dart
- packages/clerk_auth/test/unit/clerk_api/clerk_api_test.dart
- packages/clerk_flutter/example/lib/pages/clerk_sign_in_example.dart
- packages/clerk_flutter/lib/src/clerk_auth_state.dart
- packages/clerk_flutter/lib/src/utils/clerk_auth_config.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth.dart
- packages/clerk_flutter/test/widgets/clerk_loading_overlay_test.dart
> feat: add persistor and httpservice to clarkauthconfig [#183]

- packages/clerk_auth/lib/src/clerk_auth/auth.dart
> fix: update sessiontokenstream when session token is updated [#221]

- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_in_panel.dart
> fix: allow obscuration on sign in password to be togglable [#223]

- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_flutter/l10n/en.arb
- packages/clerk_flutter/lib/src/generated/clerk_sdk_localizations.dart
- packages/clerk_flutter/lib/src/generated/clerk_sdk_localizations_en.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_authentication.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_in_panel.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_up_panel.dart
> fix: enable legal consent confirmation [#222]

- packages/clerk_flutter/lib/src/widgets/ui/clerk_panel_header.dart
> fix: allow landscape logos to look better in components [#225]

- packages/clerk_auth/lib/src/models/client/user_public.dart
- packages/clerk_auth/lib/src/models/client/user_public.g.dart
- packages/clerk_auth/test/integration/clerk_api/sign_in_test.dart
- packages/clerk_auth/test/integration/clerk_api/sign_up_test.dart
> fix: ensure decoding of UserPublic.identifier is optional [#256]

- packages/clerk_auth/lib/src/clerk_api/api.dart
- packages/clerk_auth/lib/src/clerk_auth/auth.dart
- packages/clerk_auth/lib/src/models/client.dart
- packages/clerk_auth/lib/src/models/client/auth_object.dart
- packages/clerk_auth/lib/src/models/client/field.dart
- packages/clerk_auth/lib/src/models/client/permission.dart
- packages/clerk_auth/lib/src/models/client/sign_in.dart
- packages/clerk_auth/lib/src/models/client/sign_in.g.dart
- packages/clerk_auth/lib/src/models/client/sign_up.dart
- packages/clerk_auth/lib/src/models/client/strategy.dart
- packages/clerk_auth/lib/src/models/enums.dart
- packages/clerk_auth/lib/src/models/enums.g.dart
- packages/clerk_auth/lib/src/models/environment/user_settings.g.dart
- packages/clerk_auth/lib/src/models/status.dart
- packages/clerk_flutter/README.md
- packages/clerk_flutter/example/android/app/src/main/AndroidManifest.xml
- packages/clerk_flutter/example/lib/main.dart
- packages/clerk_flutter/lib/src/clerk_auth_state.dart
- packages/clerk_flutter/lib/src/utils/clerk_auth_config.dart
- packages/clerk_flutter/lib/src/utils/localization_extensions.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_authentication.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_oauth_panel.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_in_panel.dart
- packages/clerk_flutter/lib/src/widgets/authentication/clerk_sign_up_panel.dart
- packages/clerk_flutter/lib/src/widgets/control/clerk_auth.dart
- packages/clerk_flutter/lib/src/widgets/ui/or_divider.dart
- packages/clerk_flutter/lib/src/widgets/ui/strategy_button.dart
- packages/clerk_flutter/lib/src/widgets/ui/style/text_style.dart
- packages/clerk_flutter/lib/src/widgets/user/connect_account_panel.dart
> feat: enable sign up with enterprise sso [#247]

- packages/clerk_flutter/lib/src/utils/clerk_sdk_grammar.dart
> fix: enable re-initialisation of clerksdkgrammar [#261]

- packages/clerk_auth/lib/src/utils/json_serialization_helpers.dart
- packages/clerk_auth/test/unit/utils/json_serialization_helpers_test.dart
Required fields currently not updating when call updateUser in clerk_auth
@fhdeodato @shinyford
> Fix required fields currently not updating when call updateUser
